version: "3.5"
services:
  dev-php:
    image: "php:${PHP}-apache"
    ports: 
    - "${LOCAL_PORT}:80"
    volumes:
      - ./www/:/var/www/
    command: bash -c "apt-get update && apt-get upgrade -y && apachectl -D FOREGROUND"